FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk-amd64/

ADD {{ url.elasticsearch.repo }}/elasticsearch-{{ elasticsearch_version }}.tar.gz /tmp/elasticsearch.tar.gz

RUN apt-get -y install --no-install-recommends -t jessie-backports openjdk-8-jre \
    && apt-get clean

RUN useradd --user-group elasticsearch \
    && usermod -a -G microservices elasticsearch \
    && cd /usr/share \
    && tar xf /tmp/elasticsearch.tar.gz \
    && rm /tmp/elasticsearch.tar.gz \
    && mv elasticsearch-{{ elasticsearch_version }} elasticsearch \
    && chown -R elasticsearch:elasticsearch /usr/share/elasticsearch

# by default elasticsearch shell is /bin/false, we need
# /bin/bash to run elasticsearch as non-root
# https://discuss.elastic.co/t/running-as-non-root-user-service-wrapper-has-changed/7863
RUN usermod -s /bin/bash elasticsearch -d /usr/share/elasticsearch

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install io.fabric8:elasticsearch-cloud-kubernetes:5.2.2

USER elasticsearch
