FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk-amd64/

RUN apt-get -y install --no-install-recommends -t jessie-backports openjdk-8-jre \
    && apt-get clean

RUN curl {{ url.elasticsearch.gpg_key }} | sudo apt-key add - \
    && apt-get update \
    && echo "deb {{ url.elasticsearch.deb }} stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{{ elasticsearch_major_version}}.list

RUN dpkg-divert --rename /usr/lib/sysctl.d/elasticsearch.conf \
    && apt-get update \
    && apt-get install -y --no-install-recommends "elasticsearch={{ elasticsearch_version }}"

RUN usermod -a -G microservices elasticsearch \
    && chown -R elasticsearch:elasticsearch /usr/share/elasticsearch

# by default elasticsearch shell is /bin/false, we need
# /bin/bash to run elasticsearch as non-root
# https://discuss.elastic.co/t/running-as-non-root-user-service-wrapper-has-changed/7863
RUN usermod -s /bin/bash elasticsearch -d /usr/share/elasticsearch

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install io.fabric8:elasticsearch-cloud-kubernetes:5.2.2

USER elasticsearch
